import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Parlour Admin Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            {children}
        </>
    );
}